spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    jdbc-url: 'jdbc:postgresql://localhost:3306/guoyu'
    username: 'root'
    password: '210208'


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
        format_sql: false
#        physical_naming_strategy: 'com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy'
        physical_naming_strategy: 'com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy'
  liquibase:
    change-log: 'classpath:db/liquibase-changelog-master.xml'
    contexts: 'test-data'
